kind: Pod
apiVersion: v1
metadata:
        name: testpod3
spec:
        containers:
                - name: c00
                  image: ubuntu
                  command: ["/bin/bash", "-c", "while true; do echo Hello Musraful; sleep 5 ; done"]
                - name: c01
                  image: ubuntu
                  command: ["/bin/bash", "-c", "while true; do echo Hello gg sadda name Musraful; sleep 5; done"]
